package: ktablemanager
author: Daniel Planötscher, Michael Rainer
supportpage: https://github.com/kreatifIT/ktablemanager/
version: '1.0.1'

"require": {
    "php": ">=7.4",
}
requires:
    redaxo: '>=5.12'
    packages:
        yform: '>=3.4'
        yform_usability: '>=1.10'

page:
    title: translate:title
    perm: ktablemanager[]
    icon: rex-icon fa-gear
