package: ktablemanager
author: Daniel Planötscher, Michael Rainer
supportpage: https://github.com/kreatifIT/ktablemanager/
version: '1.0.0'

requires:
    redaxo: '>=5.14'
    packages:
        yform: '>=4.0'
        yform_usability: ^2.0

page:
    title: translate:title
    perm: ktablemanager[]
    icon: rex-icon fa-gear
